name: Condor Support Request Form
description: Use this form to specify detailed information about an issue you are having with Condor which requires technical support. 
title: '[Condor-Release]: Specify your issue briefly'
labels:
  - condor-issues
assignees:
  - melpadden
  - sczembor
  - dylanireland
body:
  - type: markdown
    attributes:
      value: |
        This is a feedback form, to consolidate Condor support requests.
  - type: dropdown
    id: type
    attributes:
      label: Category
      description: Please choose the category that best describes your needs.
      options:
        - Possible Bug
        - Breaking Change/Compatibility Issue
        - Integration Issue
        - Lack of documentation/Request for Information
        - Request for Tech Support
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      placeholder: john@doe.com
    validations:
      required: true
  - type: input
    id: project-name
    attributes:
      label: Project Name(Optional)
      placeholder: Your Project Here
      description: Name of the project with Casper, if applicable
    validations:
      required: false
  - type: dropdown
    id: casper-network
    attributes:
      label: Casper Network
      description: Please choose the network or environment related to the feedback, bug, or issue.
      options:
        - Devnet
        - Integration-Test
        - Testnet
        - Mainnet        
        - NCTL/Localnet
        - Other        
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Priority
      description: Please let us know if this is a blocking issue to your integration efforts
      options:
        - Low
        - Medium
        - High
        - Critical
        - Blocking/Most Urgent
        - Other
    validations:
      required: true
  - type: dropdown
    id: node-functionality
    attributes:
      label: Node Functionality
      description: Please specify the area of the Condor software concerned
      options:
        - Node
        - JSON RPC
        - Execution Engine
        - SSE
        - NCTL
        - CCTL
        - Validator
        - Consensus
        - Other
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      placeholder: Please describe your issue here.
      description: Please provide a detailed description of your issue.
    validations:
      required: true
  - type: input
    id: date-since
    attributes:
      label: Date Issue Began(optional)
      placeholder: dd/mm/yyyy
      description: When did you first notice this issue? 
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: Attachments (optional)
      description: Please attach any logs, screenshots, or links that may help with the analysis.
    validations:
      required: false